#!/bin/bash
#$ -S /bin/bash
#$ -cwd                        # Job runs in current directory (where you run qsub)
#$ -V                          # Job inherits environment (settings from loaded modules etc)
#$ -pe smp.pe 16               # Reserve whole node.
#$ -l ivybridge
#$ -t 1-5

FULL_RUNCOMMAND=`awk "NR==$SGE_TASK_ID" weak_testlist_np16.list`
$FULL_RUNCOMMAND

mv weak_matcat_np16.qsub.*.$SGE_TASK_ID ./weak_qsub_output/



