#!/bin/bash

# -- SGE options (whose lines must begin with #$)

#$ -S /bin/bash       # Our jobscript is written for the bash shell
#$ -V                 # Inherit environment settings (e.g., from loaded modulefiles)
#$ -cwd               # Run the job in the current directory

# -- the commands to be executed (programs to be run) on a compute node:


mpirun -np 1 ./sq_lgr --dist_prob --trilinos_solver --prob_id 11 --w_solver 0 --ns_solver 1 --p_solver 0 --f_solver 96 --f_amg_iter 1 --f_amg_smiter 2 --f_amg_com_smoo 9 --f_amg_damp -1 --f_amg_str 0.25 --f_amg_coarse 1 --visc 0 --ang 0 --rey 0 --noel 256 --itstimedir res_iterations


