#!/bin/bash
#$ -S /bin/bash
#$ -cwd                        # Job runs in current directory (where you run qsub)
#$ -V                          # Job inherits environment (settings from loaded modules etc)
#$ -pe smp.pe 24               # Reserve whole node.
#$ -l haswell
#$ -t 1-5

FULL_RUNCOMMAND=`awk "NR==$SGE_TASK_ID" testlist_ndof200000_np2.list`
$FULL_RUNCOMMAND

mv awlgr_ndof200000_np2.qsub.*.$SGE_TASK_ID ./qsub_output/



