#!/bin/bash
#$ -S /bin/bash
#$ -cwd                        # Job runs in current directory (where you run qsub)
#$ -V                          # Job inherits environment (settings from loaded modules etc)
#$ -pe smp.pe 16               # Reserve whole node.
#$ -l ivybridge
#$ -t 1-10
export OMP_NUM_THREADS=1

FULL_RUNCOMMAND=`awk "NR==$SGE_TASK_ID" testlist_ndof200000_np1.list`
$FULL_RUNCOMMAND

mv testlist_ndof200000_np1.qsub.*.$SGE_TASK_ID ./qsub_output/



