#!/bin/bash
#$ -S /bin/bash
#$ -cwd                        # Job runs in current directory (where you run qsub)
#$ -V                          # Job inherits environment (settings from loaded modules etc)
#$ -pe smp.pe 16               # Reserve whole node.
#$ -l ivybridge                # Uses max 4GB per core.
#$ -t 1-5

cat /proc/cpuinfo

FULL_RUNCOMMAND=`awk "NR==$SGE_TASK_ID" testlist_ndof200000_np1.list`
$FULL_RUNCOMMAND

mv awlgr_ndof200000_np1.qsub.*.$SGE_TASK_ID ./qsub_output/

cat $PE_HOSTFILE

qstat -j $JOB_ID | grep mem

